FROM public.ecr.aws/docker/library/node:22-bookworm-slim

WORKDIR /app

ENV NEXT_TELEMETRY_DISABLED=1

COPY package.json ./package.json
COPY apps/admin/package.json ./apps/admin/package.json
COPY apps/storefront/package.json ./apps/storefront/package.json
COPY packages/contracts/package.json ./packages/contracts/package.json
COPY packages/commerce-core/package.json ./packages/commerce-core/package.json
COPY packages/ui/package.json ./packages/ui/package.json

RUN npm install --no-audit --no-fund

COPY . .

RUN rm -rf apps/admin/.next apps/storefront/.next

RUN npm run build:storefront

ENV NODE_ENV=production
ENV HOSTNAME=0.0.0.0
ENV PORT=8080

EXPOSE 8080

CMD ["npm","run","start:storefront"]
