FROM public.ecr.aws/docker/library/node:22-bookworm-slim

WORKDIR /app
ENV NEXT_TELEMETRY_DISABLED=1

ARG NEXT_PUBLIC_SITE_URL
ARG NEXT_PUBLIC_ADMIN_URL
ARG NEXT_PUBLIC_SUPABASE_URL
ARG NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY
ARG NEXT_PUBLIC_USE_SUPABASE_CATALOG
ARG NEXT_PUBLIC_FAST_NAVIGATION_MODE
ARG NEXT_PUBLIC_CATALOG_REVALIDATE_SECONDS
ARG NEXT_PUBLIC_ROSTA_INSTAGRAM_URL
ARG NEXT_PUBLIC_ROSTA_TIKTOK_URL
ARG NEXT_PUBLIC_ROSTA_WHATSAPP_URL
ARG NEXT_PUBLIC_ROSTA_SUPPORT_EMAIL

ENV NEXT_PUBLIC_SITE_URL=${NEXT_PUBLIC_SITE_URL} \
    NEXT_PUBLIC_ADMIN_URL=${NEXT_PUBLIC_ADMIN_URL} \
    NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL} \
    NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY=${NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY} \
    NEXT_PUBLIC_USE_SUPABASE_CATALOG=${NEXT_PUBLIC_USE_SUPABASE_CATALOG} \
    NEXT_PUBLIC_FAST_NAVIGATION_MODE=${NEXT_PUBLIC_FAST_NAVIGATION_MODE} \
    NEXT_PUBLIC_CATALOG_REVALIDATE_SECONDS=${NEXT_PUBLIC_CATALOG_REVALIDATE_SECONDS} \
    NEXT_PUBLIC_ROSTA_INSTAGRAM_URL=${NEXT_PUBLIC_ROSTA_INSTAGRAM_URL} \
    NEXT_PUBLIC_ROSTA_TIKTOK_URL=${NEXT_PUBLIC_ROSTA_TIKTOK_URL} \
    NEXT_PUBLIC_ROSTA_WHATSAPP_URL=${NEXT_PUBLIC_ROSTA_WHATSAPP_URL} \
    NEXT_PUBLIC_ROSTA_SUPPORT_EMAIL=${NEXT_PUBLIC_ROSTA_SUPPORT_EMAIL}

COPY . .
RUN npm install --no-audit --no-fund
RUN npm run build:storefront

ENV NODE_ENV=production
ENV HOSTNAME=0.0.0.0
ENV PORT=3000
ENV ROSTA_APP=storefront

EXPOSE 3000
CMD ["npm", "run", "start:storefront"]
