"use client";

import Link from "next/link";
import { ArrowLeft, ArrowRight, Cake, Coins, Gift, History, MinusCircle, PlusCircle, RefreshCw, Save, Search, UsersRound } from "lucide-react";
import { useCallback, useEffect, useMemo, useState } from "react";
import { adminRequest } from "@/lib/adminApi";
import {
  ExactButton, ExactDetailDrawer, ExactField, ExactFormModal, ExactIconButton, ExactPageHeader,
  ExactSearchInput, ExactSegmentedControl, ExactSkeleton, ExactStatusBadge, exactFormInputClass, useExactToast,
} from "./primitives";
import { ExactAvatar, ExactDataTable, ExactEmptyState, ExactMetricCard, type ExactColumn } from "./data";

type Customer = { id: string; auth_user_id?: string | null; is_legacy_member?: boolean; is_member?: boolean; membership_source?: "new_site" | "ikas" | null; full_name: string | null; email: string | null; phone: string | null; reward_points_balance: number; birthday_reward_points: number; created_at: string | null };
type Transaction = { id: string; amount: number; balance_after: number; transaction_type: string; reason: string | null; reference_type: string | null; reference_id: string | null; created_at: string };
type Summary = { customerCount: number; memberCount: number; nonMemberCount: number; totalPoints: number; customersWithPoints: number };
type RewardSettings = { signupPoints: number; birthdayPoints: number; updatedAt: string | null; updatedByProfileId: string | null };
type Pagination = { page: number; pageSize: number; total: number; totalPages: number };
type Operation = "add" | "remove";
const emptySummary: Summary = { customerCount: 0, memberCount: 0, nonMemberCount: 0, totalPoints: 0, customersWithPoints: 0 };
const emptyPagination: Pagination = { page: 1, pageSize: 25, total: 0, totalPages: 1 };
const emptySettings: RewardSettings = { signupPoints: 2000, birthdayPoints: 0, updatedAt: null, updatedByProfileId: null };
const transactionLabels: Record<string,string> = { admin_adjustment:"Panel işlemi", order_earned:"Sipariş kazancı", order_spent:"Siparişte kullanım", birthday:"Doğum günü", welcome:"Hoş geldin" };
function nameOf(customer: Customer) { return customer.full_name || customer.email || customer.phone || "İsimsiz müşteri"; }
function points(value: number) { return Math.max(0, Math.floor(Number(value || 0))).toLocaleString("tr-TR"); }
function dateTime(value?: string | null) { const date = new Date(value || ""); return Number.isNaN(date.getTime()) ? "—" : new Intl.DateTimeFormat("tr-TR",{day:"2-digit",month:"short",year:"numeric",hour:"2-digit",minute:"2-digit"}).format(date); }
function configuredPoints(value: string) { const parsed = Number(value); if (!Number.isSafeInteger(parsed) || parsed < 0 || parsed > 10_000_000) throw new Error("Ödül puanı 0 ile 10.000.000 arasında tam sayı olmalı."); return parsed; }

export function ExactRuthiePoints() {
  const toast=useExactToast();
  const [customers,setCustomers]=useState<Customer[]>([]);
  const [summary,setSummary]=useState<Summary>(emptySummary);
  const [pagination,setPagination]=useState<Pagination>(emptyPagination);
  const [transactions,setTransactions]=useState<Transaction[]>([]);
  const [selected,setSelected]=useState<Customer|null>(null);
  const [selectedIds,setSelectedIds]=useState<string[]>([]);
  const [query,setQuery]=useState("");
  const [page,setPage]=useState(1);
  const [operation,setOperation]=useState<Operation>("add");
  const [amount,setAmount]=useState("");
  const [reason,setReason]=useState("");
  const [bulkOperation,setBulkOperation]=useState<Operation>("add");
  const [bulkAmount,setBulkAmount]=useState("");
  const [bulkReason,setBulkReason]=useState("");
  const [bulkOpen,setBulkOpen]=useState(false);
  const [settings,setSettings]=useState<RewardSettings>(emptySettings);
  const [signupPoints,setSignupPoints]=useState(String(emptySettings.signupPoints));
  const [birthdayPoints,setBirthdayPoints]=useState(String(emptySettings.birthdayPoints));
  const [settingsOpen,setSettingsOpen]=useState(false);
  const [loading,setLoading]=useState(true);
  const [busy,setBusy]=useState<string|null>(null);

  const loadSettings=useCallback(async()=>{try{const result=await adminRequest<{settings?:RewardSettings}>("/api/ruthie-points?settingsOnly=1",{force:true});const next=result.settings||emptySettings;setSettings(next);setSignupPoints(String(next.signupPoints));setBirthdayPoints(String(next.birthdayPoints));}catch(caught){toast.error(caught instanceof Error?caught.message:"ROSTA Points ayarları alınamadı.");}},[toast]);
  const load=useCallback(async(targetPage=page,profileId?:string|null)=>{setLoading(true);try{const params=new URLSearchParams({page:String(targetPage),pageSize:"25"});if(query.trim())params.set("q",query.trim());if(profileId)params.set("profileId",profileId);const result=await adminRequest<{customers?:Customer[];summary?:Summary;pagination?:Pagination;transactions?:Transaction[]}>(`/api/ruthie-points?${params.toString()}`);const next=result.customers||[];setCustomers(next);setSummary(result.summary||emptySummary);setPagination(result.pagination||{...emptyPagination,page:targetPage});setPage(result.pagination?.page||targetPage);setTransactions(profileId?result.transactions||[]:[]);setSelected((current)=>current?next.find((customer)=>customer.id===current.id)||current:null);}catch(caught){toast.error(caught instanceof Error?caught.message:"ROSTA Points bilgileri alınamadı.");}finally{setLoading(false);}},[page,query,toast]);
  useEffect(()=>{void loadSettings();},[loadSettings]);
  useEffect(()=>{const timer=window.setTimeout(()=>void load(1,null),query?250:0);return()=>window.clearTimeout(timer);},[query]);
  const allSelected=customers.length>0&&customers.every((customer)=>selectedIds.includes(customer.id));
  const settingsDirty=signupPoints!==String(settings.signupPoints)||birthdayPoints!==String(settings.birthdayPoints);

  const saveSettings=async()=>{setBusy("settings");try{const nextSignup=configuredPoints(signupPoints);const nextBirthday=configuredPoints(birthdayPoints);const result=await adminRequest<{settings?:RewardSettings}>("/api/ruthie-points",{method:"PUT",body:JSON.stringify({signupPoints:nextSignup,birthdayPoints:nextBirthday})});const next=result.settings||{signupPoints:nextSignup,birthdayPoints:nextBirthday,updatedAt:new Date().toISOString(),updatedByProfileId:null};setSettings(next);setSignupPoints(String(next.signupPoints));setBirthdayPoints(String(next.birthdayPoints));setSettingsOpen(false);toast.success("Ödül ayarları kaydedildi.");}catch(caught){toast.error(caught instanceof Error?caught.message:"Ödül ayarları kaydedilemedi.");}finally{setBusy(null);}};
  const selectCustomer=async(customer:Customer)=>{setSelected(customer);setTransactions([]);setBusy(`history:${customer.id}`);try{const params=new URLSearchParams({page:String(page),pageSize:"25",profileId:customer.id});if(query.trim())params.set("q",query.trim());const result=await adminRequest<{transactions?:Transaction[]}>(`/api/ruthie-points?${params.toString()}`);setTransactions(result.transactions||[]);}catch(caught){toast.error(caught instanceof Error?caught.message:"Puan geçmişi alınamadı.");}finally{setBusy(null);}};
  const adjust=async()=>{if(!selected)return;const value=Math.floor(Number(amount));if(!Number.isFinite(value)||value<=0){toast.error("Geçerli bir puan miktarı gir.");return;}setBusy("adjust");try{const result=await adminRequest<{appliedAmount?:number;balance?:number}>("/api/ruthie-points",{method:"POST",body:JSON.stringify({profileId:selected.id,operation,points:value,reason})});const applied=Number(result.appliedAmount||(operation==="add"?value:-value));const balance=Number(result.balance??Math.max(0,selected.reward_points_balance+applied));setCustomers((current)=>current.map((customer)=>customer.id===selected.id?{...customer,reward_points_balance:balance}:customer));const next={...selected,reward_points_balance:balance};setSelected(next);setAmount("");setReason("");toast.success(`${nameOf(selected)} için ${Math.abs(applied).toLocaleString("tr-TR")} puan ${applied>=0?"eklendi":"çıkarıldı"}.`);await selectCustomer(next);}catch(caught){toast.error(caught instanceof Error?caught.message:"Puan güncellenemedi.");}finally{setBusy(null);}};
  const adjustBulk=async()=>{const value=Math.floor(Number(bulkAmount));if(!selectedIds.length||!Number.isFinite(value)||value<=0){toast.error("Toplu işlem için müşteri ve geçerli puan miktarı seç.");return;}setBusy("bulk");try{const result=await adminRequest<{successCount?:number;failedCount?:number}>("/api/ruthie-points",{method:"POST",body:JSON.stringify({profileIds:selectedIds,operation:bulkOperation,points:value,reason:bulkReason})});toast.success(`${Number(result.successCount||0)} müşterinin puanı güncellendi${result.failedCount?`, ${result.failedCount} başarısız`:""}.`);setBulkOpen(false);setSelectedIds([]);setBulkAmount("");setBulkReason("");await load(page,null);}catch(caught){toast.error(caught instanceof Error?caught.message:"Toplu puan işlemi tamamlanamadı.");}finally{setBusy(null);}};
  const toggleAll=()=>{const ids=customers.map((customer)=>customer.id);setSelectedIds((current)=>allSelected?current.filter((id)=>!ids.includes(id)):[...new Set([...current,...ids])]);};
  const columns:ExactColumn<Customer>[]=[
    {key:"select",label:"",render:(customer)=><input type="checkbox" checked={selectedIds.includes(customer.id)} onChange={(event)=>{event.stopPropagation();setSelectedIds((current)=>current.includes(customer.id)?current.filter((id)=>id!==customer.id):[...current,customer.id]);}}/>},
    {key:"full_name",label:"Müşteri",sortable:true,render:(customer)=><div className="flex items-center gap-2"><ExactAvatar name={nameOf(customer)} size="sm"/><div><p className="ruth-type-table font-medium text-main">{nameOf(customer)}</p><p className="ruth-type-caption text-subtle">{customer.email||customer.phone||"İletişim yok"}</p></div></div>},
    {key:"is_member",label:"Üyelik",align:"center",render:(customer)=><ExactStatusBadge status={customer.is_member?"active":"archived"} label={customer.is_member?(customer.membership_source==="ikas"?"Geçiş hesabı":"ROSTA hesabı"):"Üye değil"} size="sm"/>},
    {key:"reward_points_balance",label:"Bakiye",sortable:true,align:"right",render:(customer)=><span className="ruth-type-metric text-accent">{points(customer.reward_points_balance)}</span>},
    {key:"birthday_reward_points",label:"Doğum Günü",align:"right",render:(customer)=><span className="ruth-type-table tabular-nums text-muted">{points(customer.birthday_reward_points)}</span>},
    {key:"created_at",label:"Kayıt",sortable:true,render:(customer)=><span className="ruth-type-code text-muted">{dateTime(customer.created_at)}</span>},
  ];

  return <div className="space-y-4 animate-fade-in" data-exact-base44-page="rosta-points">
    <ExactPageHeader title="ROSTA Points" subtitle={`${pagination.total} müşteri · ${points(summary.totalPoints)} toplam puan`} actions={<><Link href="/customers"><ExactButton variant="secondary" size="sm"><ArrowLeft className="h-4 w-4"/> Müşteriler</ExactButton></Link><ExactButton variant="secondary" size="sm" onClick={()=>setSettingsOpen(true)}><Gift className="h-4 w-4"/> Ödül ayarları</ExactButton><ExactButton size="sm" onClick={()=>setBulkOpen(true)} disabled={!selectedIds.length}><UsersRound className="h-4 w-4"/> Toplu puan ({selectedIds.length})</ExactButton><ExactIconButton icon={RefreshCw} label="Yenile" variant="secondary" onClick={()=>{void loadSettings();void load(page,selected?.id||null);}} loading={loading}/></>} />
    <div className="grid grid-cols-2 lg:grid-cols-4 gap-3"><ExactMetricCard label="Üyeler" value={summary.memberCount} icon={UsersRound}/><ExactMetricCard label="Puanlı Müşteri" value={summary.customersWithPoints} icon={Coins}/><ExactMetricCard label="Toplam Puan" value={summary.totalPoints} icon={Gift}/><ExactMetricCard label="Hoş Geldin Puanı" value={settings.signupPoints} icon={PlusCircle}/></div>
    <div className="flex flex-col sm:flex-row gap-3"><label className="ruth-type-control flex items-center gap-2 text-muted sm:w-auto"><input type="checkbox" checked={allSelected} onChange={toggleAll}/> Sayfadakilerin tümünü seç</label><ExactSearchInput value={query} onChange={setQuery} placeholder="İsim, e-posta veya telefon ara..." className="flex-1"/></div>
    {loading?<div className="space-y-2"><ExactSkeleton className="h-16"/><ExactSkeleton className="h-16"/><ExactSkeleton className="h-16"/></div>:<ExactDataTable columns={columns} data={customers} onRowClick={(customer)=>void selectCustomer(customer)} emptyState={<ExactEmptyState icon={Coins} title="Müşteri bulunamadı"/>}/>} 
    {!loading&&pagination.totalPages>1?<div className="flex items-center justify-center gap-3"><ExactButton variant="secondary" size="sm" disabled={pagination.page<=1} onClick={()=>void load(pagination.page-1,null)}><ArrowLeft className="h-4 w-4"/> Önceki</ExactButton><span className="ruth-type-caption text-muted">{pagination.page} / {pagination.totalPages}</span><ExactButton variant="secondary" size="sm" disabled={pagination.page>=pagination.totalPages} onClick={()=>void load(pagination.page+1,null)}>Sonraki <ArrowRight className="h-4 w-4"/></ExactButton></div>:null}
    <ExactDetailDrawer open={Boolean(selected)} onClose={()=>{if(!busy)setSelected(null);}} title={selected?nameOf(selected):"Müşteri"} subtitle={selected?`${points(selected.reward_points_balance)} ROSTA Points`:undefined} width={660} footer={selected?<ExactButton variant="secondary" size="sm" className="w-full" onClick={()=>setSelected(null)}>Kapat</ExactButton>:null}>
      {selected?<div className="space-y-5"><div className="flex items-center gap-3"><ExactAvatar name={nameOf(selected)} size="lg"/><div><p className="ruth-type-card-title text-main">{nameOf(selected)}</p><p className="ruth-type-caption text-muted">{selected.email||selected.phone}</p></div><div className="ml-auto text-right"><p className="ruth-type-metric text-accent">{points(selected.reward_points_balance)}</p><p className="ruth-type-label text-subtle">mevcut bakiye</p></div></div><section><div className="flex items-center gap-2 mb-2"><Coins className="h-3.5 w-3.5 text-subtle"/><h4 className="ruth-type-label font-semibold text-muted uppercase tracking-wide">Puan düzenle</h4></div><ExactSegmentedControl size="sm" value={operation} onChange={(value)=>setOperation(value as Operation)} options={[{value:"add",label:"Puan ekle",icon:PlusCircle},{value:"remove",label:"Puan çıkar",icon:MinusCircle}]}/><div className="grid sm:grid-cols-2 gap-3 mt-3"><ExactField label="Miktar"><input type="number" min="1" value={amount} onChange={(e)=>setAmount(e.target.value)} className={exactFormInputClass}/></ExactField><ExactField label="Sebep"><input value={reason} onChange={(e)=>setReason(e.target.value)} className={exactFormInputClass} placeholder="Kampanya, telafi, düzeltme..."/></ExactField></div><ExactButton size="sm" className="w-full mt-3" onClick={()=>void adjust()} loading={busy==="adjust"}>{operation==="add"?"Puan ekle":"Puan çıkar"}</ExactButton></section><section><div className="flex items-center gap-2 mb-2"><History className="h-3.5 w-3.5 text-subtle"/><h4 className="ruth-type-label font-semibold text-muted uppercase tracking-wide">Hareket geçmişi</h4></div>{busy===`history:${selected.id}`?<ExactSkeleton className="h-32"/>:<div className="space-y-2">{transactions.map((transaction)=><div key={transaction.id} className="flex items-center gap-3 p-2.5 radius-small bg-surface-secondary"><div className={`flex items-center justify-center h-8 w-8 radius-small ${transaction.amount>=0?"bg-success-soft text-success-foreground":"bg-danger-soft text-danger-foreground"}`}>{transaction.amount>=0?<PlusCircle className="h-4 w-4"/>:<MinusCircle className="h-4 w-4"/>}</div><div className="flex-1"><p className="ruth-type-table font-medium text-main">{transactionLabels[transaction.transaction_type]||transaction.transaction_type}</p><p className="ruth-type-code text-muted">{transaction.reason||"Açıklama yok"} · {dateTime(transaction.created_at)}</p></div><div className="text-right"><p className={`ruth-type-metric ${transaction.amount>=0?"text-success-foreground":"text-danger-foreground"}`}>{transaction.amount>=0?"+":""}{transaction.amount}</p><p className="ruth-type-code text-subtle">{points(transaction.balance_after)}</p></div></div>)}{!transactions.length?<ExactEmptyState compact icon={History} title="Hareket yok"/>:null}</div>}</section></div>:null}
    </ExactDetailDrawer>
    <ExactFormModal open={settingsOpen} onClose={()=>setSettingsOpen(false)} title="ROSTA Points ödül ayarları" subtitle="Yeni üyelik ve doğum günü ödülleri" size="md" footer={<><ExactButton variant="secondary" size="sm" onClick={()=>setSettingsOpen(false)}>Vazgeç</ExactButton><ExactButton size="sm" onClick={()=>void saveSettings()} loading={busy==="settings"} disabled={!settingsDirty}><Save className="h-4 w-4"/> Kaydet</ExactButton></>}><div className="grid sm:grid-cols-2 gap-3"><ExactField label="Yeni üyelik puanı"><input type="number" min="0" value={signupPoints} onChange={(e)=>setSignupPoints(e.target.value)} className={exactFormInputClass}/></ExactField><ExactField label="Doğum günü puanı"><input type="number" min="0" value={birthdayPoints} onChange={(e)=>setBirthdayPoints(e.target.value)} className={exactFormInputClass}/></ExactField></div><p className="ruth-type-caption text-muted mt-3">Değişiklik yalnızca bundan sonra hak kazanan üyeleri etkiler; mevcut bakiyeler değişmez.</p></ExactFormModal>
    <ExactFormModal open={bulkOpen} onClose={()=>setBulkOpen(false)} title={`Toplu puan işlemi · ${selectedIds.length} müşteri`} size="md" footer={<><ExactButton variant="secondary" size="sm" onClick={()=>setBulkOpen(false)}>Vazgeç</ExactButton><ExactButton size="sm" onClick={()=>void adjustBulk()} loading={busy==="bulk"}>Uygula</ExactButton></>}><ExactSegmentedControl size="sm" value={bulkOperation} onChange={(value)=>setBulkOperation(value as Operation)} options={[{value:"add",label:"Puan ekle"},{value:"remove",label:"Puan çıkar"}]}/><div className="grid sm:grid-cols-2 gap-3 mt-3"><ExactField label="Miktar"><input type="number" min="1" value={bulkAmount} onChange={(e)=>setBulkAmount(e.target.value)} className={exactFormInputClass}/></ExactField><ExactField label="Sebep"><input value={bulkReason} onChange={(e)=>setBulkReason(e.target.value)} className={exactFormInputClass}/></ExactField></div></ExactFormModal>
  </div>;
}
