"use client";

import { BarChart3, CircleDollarSign, Download, Package, ShoppingBag, TrendingUp, Users } from "lucide-react";
import { useCallback, useEffect, useMemo, useState } from "react";
import { adminRequest } from "@/lib/adminApi";
import { ExactButton, ExactPageHeader, ExactSegmentedControl, ExactSkeleton, useExactToast } from "./primitives";
import { ExactDataCard, ExactMetricCard } from "./data";

type Focus = "sales" | "products" | "customers" | "operations";
type OrderItem = { product_name?: string; quantity?: number; total_price?: number };
type Order = { id: string; total_amount: number; payment_status: string; created_at: string; traffic_source?: string | null; status?: string; order_items?: OrderItem[] };
type SummaryPayload = { summary?: { orders?: number; paidOrders?: number; revenue?: number; sessions?: number; products?: number; customers?: number; newCustomers?: number; conversionRate?: number }; recentOrders?: Order[]; operationCounts?: { newOrders?: number; preparing?: number; ready?: number; shippingAttention?: number }; paymentSummary?: { reviewRequired?: number; refundedTotal?: number } };
type Product = { id: string; name: string; status?: string; stock_status?: string; price?: number; product_variants?: Array<{ stock?: number }> };
type Customer = { id: string; order_count?: number; total_spent?: number; is_member?: boolean };
function paid(order: Order) { return ["paid", "success", "succeeded"].includes(String(order.payment_status || "").toLowerCase()); }
function money(value: number) { return new Intl.NumberFormat("tr-TR", { style: "currency", currency: "TRY", notation: "compact", maximumFractionDigits: 1 }).format(Number(value || 0)); }

function SalesChart({ orders, days }: { orders: Order[]; days: number }) {
  const data = useMemo(() => Array.from({ length: Math.min(days, 30) }, (_, index) => { const date = new Date(); date.setHours(0, 0, 0, 0); date.setDate(date.getDate() - (Math.min(days, 30) - 1 - index)); const next = new Date(date); next.setDate(next.getDate() + 1); const sales = orders.filter((order) => { const created = new Date(order.created_at); return paid(order) && created >= date && created < next; }).reduce((sum, order) => sum + Number(order.total_amount || 0), 0); return { label: days <= 1 ? "Bugün" : days <= 7 ? new Intl.DateTimeFormat("tr-TR", { weekday: "short" }).format(date) : new Intl.DateTimeFormat("tr-TR", { day: "2-digit", month: "short" }).format(date), sales }; }), [days, orders]);
  const width = 760, height = 280, left = 24, right = 16, top = 18, bottom = 34, max = Math.max(1, ...data.map((item) => item.sales));
  const points = data.map((item, index) => ({ ...item, x: left + index * (width - left - right) / Math.max(1, data.length - 1), y: top + (1 - item.sales / max) * (height - top - bottom) }));
  const polyline = points.map((point) => `${point.x},${point.y}`).join(" ");
  return <svg viewBox={`0 0 ${width} ${height}`} className="w-full h-[280px]" role="img" aria-label="Satış trendi"><defs><linearGradient id="analyticsGradient" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="hsl(var(--accent))" stopOpacity=".28"/><stop offset="100%" stopColor="hsl(var(--accent))" stopOpacity="0"/></linearGradient></defs>{[.25,.5,.75,1].map((ratio)=><line key={ratio} x1={left} x2={width-right} y1={top+ratio*(height-top-bottom)} y2={top+ratio*(height-top-bottom)} stroke="hsl(var(--border-subtle))" strokeDasharray="3 3"/>)}<polygon points={`${left},${height-bottom} ${polyline} ${width-right},${height-bottom}`} fill="url(#analyticsGradient)"/><polyline points={polyline} fill="none" stroke="hsl(var(--accent))" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round"/>{points.map((point, index)=><g key={index}><circle cx={point.x} cy={point.y} r="3" fill="hsl(var(--accent))"><title>{point.label}: {money(point.sales)}</title></circle>{(data.length <= 10 || index % Math.ceil(data.length / 7) === 0) ? <text x={point.x} y={height-10} textAnchor="middle" className="ruth-type-caption" fill="hsl(var(--text-subtle))">{point.label}</text> : null}</g>)}</svg>;
}

export function ExactAnalytics({ focus = "sales" }: { focus?: Focus }) {
  const toast = useExactToast();
  const [range, setRange] = useState("today");
  const [payload, setPayload] = useState<SummaryPayload>({});
  const [products, setProducts] = useState<Product[]>([]);
  const [customers, setCustomers] = useState<Customer[]>([]);
  const [loading, setLoading] = useState(true);
  const days = range === "today" ? 1 : range === "90d" ? 90 : range === "30d" ? 30 : 7;
  const load = useCallback(async () => { setLoading(true); try { const summaryRange = range === "today" ? "today" : range === "7d" ? "last_7_days" : range === "30d" ? "last_30_days" : "last_90_days"; const [summary, catalog, customerData] = await Promise.all([adminRequest<SummaryPayload>(`/api/summary?range=${summaryRange}`), adminRequest<{ products?: Product[] }>("/api/products?q="), adminRequest<{ customers?: Customer[] }>("/api/customers/list?page=1&pageSize=100&membership=all&sort=spent").catch(() => ({ customers: [] }))]); setPayload(summary); setProducts(catalog.products || []); setCustomers(customerData.customers || []); } catch (caught) { toast.error(caught instanceof Error ? caught.message : "Analitik verileri alınamadı."); } finally { setLoading(false); } }, [range, toast]);
  useEffect(() => { void load(); }, [load]);
  const summary = payload.summary || {};
  const orders = payload.recentOrders || [];
  const avgOrder = Number(summary.paidOrders || 0) ? Number(summary.revenue || 0) / Number(summary.paidOrders || 1) : 0;
  const topProducts = useMemo(() => { const map = new Map<string, { name: string; sales: number; revenue: number }>(); for (const order of orders) for (const item of order.order_items || []) { const name = item.product_name || "Ürün"; const current = map.get(name) || { name, sales: 0, revenue: 0 }; current.sales += Number(item.quantity || 1); current.revenue += Number(item.total_price || 0); map.set(name, current); } return [...map.values()].sort((a,b)=>b.revenue-a.revenue).slice(0,8); }, [orders]);
  const channelRows = useMemo(() => { const map = new Map<string, number>(); for (const order of orders.filter(paid)) { const channel = order.traffic_source || "Doğrudan"; map.set(channel, (map.get(channel) || 0) + Number(order.total_amount || 0)); } const total = Math.max(1, [...map.values()].reduce((a,b)=>a+b,0)); return [...map.entries()].map(([channel,value])=>({channel,value,pct:value/total*100})).sort((a,b)=>b.value-a.value).slice(0,6); }, [orders]);
  const inventory = useMemo(() => { let inStock=0, low=0, out=0, variants=0; for (const product of products) { const stock=(product.product_variants||[]).reduce((sum,v)=>sum+Number(v.stock||0),0); variants += product.product_variants?.length || 0; if (stock<=0 && product.stock_status!=="in_stock") out++; else if (stock<5) low++; else inStock++; } return {inStock,low,out,variants}; }, [products]);
  const operations = payload.operationCounts || {};
  const exportCsv = () => { const rows=[["Metrik","Değer"],["Net satış",String(summary.revenue||0)],["Sipariş",String(summary.orders||0)],["Ortalama sepet",String(avgOrder)],["Yeni müşteri",String(summary.newCustomers||0)],["Dönüşüm",String(summary.conversionRate||0)]]; const csv=rows.map(row=>row.map(value=>`"${value}"`).join(",")).join("\n"); const url=URL.createObjectURL(new Blob([`\ufeff${csv}`],{type:"text/csv;charset=utf-8"})); const a=document.createElement("a"); a.href=url; a.download=`rosta-analytics-${range}.csv`; a.click(); URL.revokeObjectURL(url); };

  return <div className="space-y-4 animate-fade-in" data-exact-base44-page={`analytics-${focus}`}>
    <ExactPageHeader title={focus === "products" ? "Ürün Analitiği" : focus === "customers" ? "Müşteri Analitiği" : focus === "operations" ? "Operasyon Analitiği" : "Analitik"} subtitle="Satış, müşteri, ürün ve operasyon içgörüleri" actions={<><ExactSegmentedControl size="sm" value={range} onChange={setRange} options={[{value:"today",label:"Bugün"},{value:"7d",label:"7G"},{value:"30d",label:"30G"},{value:"90d",label:"90G"}]} /><ExactButton variant="secondary" size="sm" onClick={exportCsv}><Download className="h-4 w-4"/> Dışa aktar</ExactButton></>} />
    {loading ? <div className="grid grid-cols-2 lg:grid-cols-4 gap-3"><ExactSkeleton className="h-32"/><ExactSkeleton className="h-32"/><ExactSkeleton className="h-32"/><ExactSkeleton className="h-32"/></div> : <div className="grid grid-cols-2 lg:grid-cols-4 gap-3"><ExactMetricCard label="Net Satış" value={Number(summary.revenue||0)} format="currency" icon={CircleDollarSign}/><ExactMetricCard label="Toplam Sipariş" value={Number(summary.orders||0)} icon={ShoppingBag}/><ExactMetricCard label="Ortalama Sepet" value={avgOrder} format="currency" icon={TrendingUp}/><ExactMetricCard label="Yeni Müşteri" value={Number(summary.newCustomers||0)} icon={Users}/></div>}
    <div className="grid grid-cols-1 lg:grid-cols-3 gap-3"><ExactDataCard title="Satış Trendi" className="lg:col-span-2" bodyClassName="pt-2"><SalesChart orders={orders} days={days}/></ExactDataCard><ExactDataCard title="En Çok Satan Ürünler"><div className="space-y-3">{topProducts.map((product,index)=><div key={product.name} className="flex items-center gap-3"><span className="ruth-type-table w-4 font-bold text-subtle">{index+1}</span><div className="flex-1 min-w-0"><p className="ruth-type-table truncate font-medium text-main">{product.name}</p><p className="ruth-type-caption text-muted">{product.sales} adet · {money(product.revenue)}</p></div><div className="h-1.5 w-12 rounded-full bg-surface-tertiary overflow-hidden"><div className="h-full rounded-full bg-accent" style={{width:`${topProducts[0]?.revenue ? product.revenue/topProducts[0].revenue*100 : 0}%`}}/></div></div>)}{!topProducts.length?<p className="ruth-type-caption py-8 text-center text-subtle">Ürün satış verisi yok</p>:null}</div></ExactDataCard></div>
    <div className="grid grid-cols-1 lg:grid-cols-2 gap-3"><ExactDataCard title="Satış Kanalları"><div className="space-y-2.5">{channelRows.map((row)=><div key={row.channel}><div className="ruth-type-table mb-1 flex justify-between"><span className="font-medium text-main">{row.channel}</span><span className="text-muted">{money(row.value)}</span></div><div className="h-2 rounded-full bg-surface-tertiary overflow-hidden"><div className="h-full rounded-full bg-accent" style={{width:`${row.pct}%`}}/></div></div>)}{!channelRows.length?<p className="ruth-type-caption py-8 text-center text-subtle">Kanal verisi yok</p>:null}</div></ExactDataCard><ExactDataCard title="Stok Sağlığı"><div className="grid grid-cols-2 gap-3"><div className="p-3 radius-small bg-success-soft"><p className="ruth-type-label uppercase text-subtle">Stokta</p><p className="ruth-type-metric text-success-foreground">{inventory.inStock}</p></div><div className="p-3 radius-small bg-warning-soft"><p className="ruth-type-label uppercase text-subtle">Düşük Stok</p><p className="ruth-type-metric text-warning-foreground">{inventory.low}</p></div><div className="p-3 radius-small bg-danger-soft"><p className="ruth-type-label uppercase text-subtle">Stok Yok</p><p className="ruth-type-metric text-danger-foreground">{inventory.out}</p></div><div className="p-3 radius-small bg-info-soft"><p className="ruth-type-label uppercase text-subtle">Varyant</p><p className="ruth-type-metric text-info-foreground">{inventory.variants}</p></div></div></ExactDataCard></div>
    <div className="grid grid-cols-2 lg:grid-cols-4 gap-3"><ExactMetricCard label="Yeni Sipariş" value={Number(operations.newOrders||0)} icon={ShoppingBag}/><ExactMetricCard label="Üretimde" value={Number(operations.preparing||0)} icon={Package}/><ExactMetricCard label="Kargoya Hazır" value={Number(operations.ready||0)} icon={BarChart3}/><ExactMetricCard label="İşlem Gereken" value={Number(operations.shippingAttention||0)+Number(payload.paymentSummary?.reviewRequired||0)} icon={TrendingUp}/></div>
    {focus === "customers" ? <ExactDataCard title="En Değerli Müşteriler"><div className="grid sm:grid-cols-2 xl:grid-cols-3 gap-2">{customers.slice(0,12).map((customer,index)=><div key={customer.id} className="p-3 radius-small bg-surface-secondary"><p className="ruth-type-label text-subtle">Müşteri #{index+1}</p><p className="ruth-type-price font-bold text-main">{money(Number(customer.total_spent||0))}</p><p className="ruth-type-caption text-muted">{customer.order_count||0} sipariş · {customer.is_member?"Üye":"Misafir"}</p></div>)}</div></ExactDataCard>:null}
  </div>;
}