"use client";

import Link from "next/link";
import { AlertTriangle, ArrowLeft, CheckCircle2, Clock3, RefreshCw, RotateCcw, ShieldAlert } from "lucide-react";
import { useCallback, useEffect, useMemo, useState } from "react";
import { adminRequest } from "@/lib/adminApi";
import { ExactButton, ExactIconButton, ExactPageHeader, ExactSkeleton, ExactStatusBadge, useExactToast } from "./primitives";
import { ExactDataCard, ExactEmptyState, ExactMetricCard } from "./data";

type OrderException={id:string;order_no:string;customer_name:string;customer_phone?:string|null;status?:string|null;shipping_status?:string|null;shipping_error?:string|null;shipping_updated_at?:string|null;cargo_company?:string|null;cargo_tracking_no?:string|null};
type WebhookRow={id:string;provider:string;event_key:string;event_type?:string|null;external_order_id?:string|null;tracking_no?:string|null;status:string;attempts:number;max_attempts:number;next_attempt_at?:string|null;last_error?:string|null;received_at:string};
type TimelineRow={id:string;order_id:string;event_type:string;from_status?:string|null;to_status?:string|null;shipment_status?:string|null;source?:string|null;reason?:string|null;occurred_at:string};
type OperationsData={counts:{orderExceptions:number;waitingWebhooks:number;failedWebhooks:number;deadLetters:number};orders:OrderException[];inbox:WebhookRow[];timeline:TimelineRow[]};
const emptyData:OperationsData={counts:{orderExceptions:0,waitingWebhooks:0,failedWebhooks:0,deadLetters:0},orders:[],inbox:[],timeline:[]};
function dateTime(value?:string|null){const date=new Date(value||"");return Number.isNaN(date.getTime())?"—":new Intl.DateTimeFormat("tr-TR",{day:"2-digit",month:"short",year:"numeric",hour:"2-digit",minute:"2-digit"}).format(date);}
function statusLabel(status:string){return status==="dead_letter"?"Müdahale gerekli":status==="failed"?"Tekrar denenecek":status==="processing"?"İşleniyor":"Kuyrukta";}
function timelineLabel(row:TimelineRow){if(row.event_type==="shipment.status_changed")return`Kargo: ${row.shipment_status||row.to_status||"—"}`;if(row.event_type==="order.status_changed")return`Sipariş: ${row.from_status||"—"} → ${row.to_status||"—"}`;return row.event_type.replaceAll("."," ");}
export function ExactShippingOperations(){
 const toast=useExactToast();const[data,setData]=useState<OperationsData>(emptyData);const[loading,setLoading]=useState(true);const[busy,setBusy]=useState<string|null>(null);
 const load=useCallback(async()=>{setLoading(true);try{const result=await adminRequest<Partial<OperationsData>>("/api/shipping/operations");setData({counts:result.counts||emptyData.counts,orders:result.orders||[],inbox:result.inbox||[],timeline:result.timeline||[]});}catch(caught){toast.error(caught instanceof Error?caught.message:"Kargo operasyonları alınamadı.");}finally{setLoading(false);}},[toast]);
 useEffect(()=>{void load();},[load]);
 const timelineByOrder=useMemo(()=>{const map=new Map<string,TimelineRow[]>();for(const row of data.timeline)map.set(row.order_id,[...(map.get(row.order_id)||[]),row]);return map;},[data.timeline]);
 const run=async(action:string,payload:Record<string,unknown>,key:string,message:string)=>{setBusy(key);try{await adminRequest("/api/shipping/operations",{method:"POST",body:JSON.stringify({action,...payload})});toast.success(message);await load();}catch(caught){toast.error(caught instanceof Error?caught.message:"İşlem tamamlanamadı.");}finally{setBusy(null);}};
 return <div className="space-y-4 animate-fade-in" data-exact-base44-page="shipping-operations"><ExactPageHeader title="Kargo İstisnaları" subtitle="Teslimat hataları, webhook kuyruğu ve dead-letter kayıtları" actions={<><Link href="/orders?queue=shipped"><ExactButton variant="secondary" size="sm"><ArrowLeft className="h-4 w-4"/> Kargo kuyruğu</ExactButton></Link><ExactIconButton icon={RefreshCw} label="Yenile" variant="secondary" onClick={()=>void load()} loading={loading}/><ExactButton size="sm" disabled={Boolean(busy)||data.counts.failedWebhooks+data.counts.deadLetters===0} onClick={()=>void run("retry_all_webhooks",{},"retry-all","Başarısız webhook kayıtları yeniden kuyruğa alındı.")} loading={busy==="retry-all"}><RotateCcw className="h-4 w-4"/> Tümünü yeniden dene</ExactButton></>}/>
 <div className="grid grid-cols-2 lg:grid-cols-4 gap-3"><ExactMetricCard label="Sipariş İstisnası" value={data.counts.orderExceptions} icon={ShieldAlert}/><ExactMetricCard label="Kuyrukta" value={data.counts.waitingWebhooks} icon={Clock3}/><ExactMetricCard label="Başarısız Webhook" value={data.counts.failedWebhooks} icon={AlertTriangle}/><ExactMetricCard label="Dead Letter" value={data.counts.deadLetters} icon={AlertTriangle}/></div>
 {loading?<div className="grid lg:grid-cols-2 gap-3"><ExactSkeleton className="h-96"/><ExactSkeleton className="h-96"/></div>:<div className="grid xl:grid-cols-2 gap-3 items-start"><ExactDataCard title="Teslimat İstisnaları" action={<ShieldAlert className="h-4 w-4 text-danger-foreground"/>}><div className="space-y-3">{data.orders.map((order)=>{const timeline=(timelineByOrder.get(order.id)||[]).slice(0,4);return <article key={order.id} className="p-3 radius-control border border-danger/20 bg-danger-soft/40"><div className="flex items-start justify-between gap-3"><div><p className="ruth-type-card-title text-main">#{order.order_no}</p><p className="ruth-type-caption text-muted">{order.customer_name} · {order.customer_phone||"Telefon yok"}</p></div><ExactStatusBadge status="failed" label={order.shipping_status||"Hata"} tone="danger" size="sm"/></div><p className="ruth-type-caption mt-3 text-danger-foreground">{order.shipping_error||"Kargo durumu ile sipariş durumu eşleşmiyor."}</p><div className="mt-3 grid grid-cols-3 gap-2"><div className="p-2 radius-small bg-surface-primary"><p className="ruth-type-label text-subtle">Firma</p><p className="ruth-type-code truncate text-main">{order.cargo_company||"—"}</p></div><div className="p-2 radius-small bg-surface-primary"><p className="ruth-type-label text-subtle">Takip no</p><p className="ruth-type-code truncate text-main">{order.cargo_tracking_no||"—"}</p></div><div className="p-2 radius-small bg-surface-primary"><p className="ruth-type-label text-subtle">Güncelleme</p><p className="ruth-type-code truncate text-main">{dateTime(order.shipping_updated_at)}</p></div></div><div className="mt-3"><div className="flex items-center justify-between"><p className="ruth-type-label font-semibold uppercase text-subtle">Operasyon timeline’ı</p><Link href={`/orders/${order.id}/timeline`} className="ruth-type-control text-accent">Tüm kayıt zinciri</Link></div><div className="space-y-2 mt-2">{timeline.map((item)=><div key={item.id} className="flex items-start gap-2"><span className="h-2 w-2 rounded-full bg-accent mt-1.5 shrink-0"/><div><p className="ruth-type-table font-medium text-main">{timelineLabel(item)}</p><p className="ruth-type-caption text-muted">{item.reason||item.source||"Sistem"} · {dateTime(item.occurred_at)}</p></div></div>)}</div></div></article>;})}{!data.orders.length?<ExactEmptyState compact icon={CheckCircle2} title="Açık teslimat istisnası yok"/>:null}</div></ExactDataCard>
 <ExactDataCard title="Webhook İşlem Kuyruğu" action={<Clock3 className="h-4 w-4 text-warning-foreground"/>}><div className="space-y-2">{data.inbox.map((row)=>{const retryable=["failed","dead_letter"].includes(row.status),key=`retry:${row.id}`;return <article key={row.id} className="p-3 radius-small bg-surface-secondary"><div className="flex items-start justify-between gap-2"><ExactStatusBadge status={row.status} label={statusLabel(row.status)} size="sm"/><span className="ruth-type-code text-subtle">{dateTime(row.received_at)}</span></div><p className="ruth-type-card-title mt-2 text-main">{row.event_type||"basit_kargo.webhook"}</p><p className="ruth-type-caption text-muted">{row.external_order_id||"Sipariş yok"} · {row.tracking_no||"Takip no yok"}</p><p className="ruth-type-caption mt-2 text-danger-foreground">{row.last_error||"Otomatik işleme bekliyor."}</p><div className="flex items-center justify-between mt-3"><span className="ruth-type-caption text-subtle">Deneme {row.attempts}/{row.max_attempts}</span>{retryable?<ExactButton variant="secondary" size="sm" onClick={()=>void run("retry_webhook",{inbox_id:row.id},key,"Webhook yeniden işlendi.")} loading={busy===key}><RotateCcw className="h-3.5 w-3.5"/> Yeniden dene</ExactButton>:<ExactStatusBadge status="processing" label="Otomatik" size="sm"/>}</div></article>;})}{!data.inbox.length?<ExactEmptyState compact icon={CheckCircle2} title="Webhook kuyruğu temiz"/>:null}</div></ExactDataCard></div>}
 </div>;
}
