"use client";

import Link from "next/link";
import { ArrowLeft, Clock3, Eye, Mail, RefreshCw, Save, Send, Sparkles } from "lucide-react";
import { useCallback, useEffect, useMemo, useState } from "react";
import { adminRequest } from "@/lib/adminApi";
import { ExactButton, ExactField, ExactIconButton, ExactPageHeader, exactFormInputClass, useExactToast } from "./primitives";
import { ExactDataCard, ExactMetricCard } from "./data";

type ReviewSettings = { enabled: boolean; delayDaysAfterDelivered: number; discountPercent: number; subject: string; template: string };
type AbandonedSettings = { enabled: boolean; firstDelayHours: number; secondDelayHours: number; thirdDelayHours: number };
type PreviewKey = "abandoned_cart_1" | "abandoned_cart_2" | "abandoned_cart_3" | "review_request";
const defaultReview: ReviewSettings = { enabled: true, delayDaysAfterDelivered: 1, discountPercent: 10, subject: "Ürünü değerlendir, %10 indirim kazan", template: "Merhaba {{customer_name}}, siparişindeki ürünleri değerlendirmek ister misin? Yorumunu gönderdiğinde %10 indirim hesabına tanımlanır. {{review_url}}" };
const defaultAbandoned: AbandonedSettings = { enabled: true, firstDelayHours: 3, secondDelayHours: 6, thirdDelayHours: 6 };
function normalizeReview(value?: Partial<ReviewSettings>): ReviewSettings { return { enabled: typeof value?.enabled === "boolean" ? value.enabled : true, delayDaysAfterDelivered: Math.max(1, Math.min(14, Number(value?.delayDaysAfterDelivered ?? 1))), discountPercent: Math.max(0, Math.min(100, Number(value?.discountPercent ?? 10))), subject: value?.subject || defaultReview.subject, template: value?.template || defaultReview.template }; }
function normalizeAbandoned(value?: Partial<AbandonedSettings>): AbandonedSettings { return { enabled: typeof value?.enabled === "boolean" ? value.enabled : true, firstDelayHours: Math.max(1, Math.min(72, Number(value?.firstDelayHours ?? 3))), secondDelayHours: Math.max(1, Math.min(72, Number(value?.secondDelayHours ?? 6))), thirdDelayHours: Math.max(1, Math.min(72, Number(value?.thirdDelayHours ?? 6))) }; }
function Toggle({ checked, onChange, label, description }: { checked: boolean; onChange: (value: boolean) => void; label: string; description: string }) { return <button type="button" onClick={() => onChange(!checked)} className="w-full flex items-center gap-3 p-3 radius-control bg-surface-secondary border border-border-subtle text-left"><span className={`relative h-6 w-10 rounded-full ${checked ? "bg-accent" : "bg-surface-tertiary"}`}><span className={`absolute top-0.5 left-0.5 h-5 w-5 rounded-full bg-white shadow-sm transition-all ${checked ? "translate-x-4" : ""}`} /></span><span className="flex-1"><strong className="block text-sm text-main">{label}</strong><small className="block text-[10px] text-muted mt-0.5">{description}</small></span><em className="not-italic text-[10px] text-subtle">{checked ? "Aktif" : "Pasif"}</em></button>; }

export function ExactAutomations() {
  const toast = useExactToast();
  const [review, setReview] = useState<ReviewSettings>(defaultReview);
  const [abandoned, setAbandoned] = useState<AbandonedSettings>(defaultAbandoned);
  const [previewKey, setPreviewKey] = useState<PreviewKey>("review_request");
  const [loading, setLoading] = useState(true);
  const [busy, setBusy] = useState<string | null>(null);
  const load = useCallback(async () => {
    setLoading(true);
    const [reviewResult, abandonedResult] = await Promise.allSettled([adminRequest<{ settings?: ReviewSettings }>("/api/review-automation/settings"), adminRequest<{ settings?: AbandonedSettings }>("/api/email/abandoned-cart/settings")]);
    if (reviewResult.status === "fulfilled") setReview(normalizeReview(reviewResult.value.settings));
    if (abandonedResult.status === "fulfilled") setAbandoned(normalizeAbandoned(abandonedResult.value.settings));
    if (reviewResult.status === "rejected" && abandonedResult.status === "rejected") toast.error("Otomasyon ayarları alınamadı.");
    setLoading(false);
  }, [toast]);
  useEffect(() => { void load(); }, [load]);
  const saveAbandoned = async () => { setBusy("abandoned-save"); try { const result = await adminRequest<{ settings?: AbandonedSettings }>("/api/email/abandoned-cart/settings", { method: "PUT", body: JSON.stringify({ settings: abandoned }) }); setAbandoned(normalizeAbandoned(result.settings)); toast.success("Terk sepet otomasyonu kaydedildi."); } catch (caught) { toast.error(caught instanceof Error ? caught.message : "Terk sepet ayarları kaydedilemedi."); } finally { setBusy(null); } };
  const saveReview = async () => { setBusy("review-save"); try { const result = await adminRequest<{ settings?: ReviewSettings }>("/api/review-automation/settings", { method: "PUT", body: JSON.stringify({ settings: review }) }); setReview(normalizeReview(result.settings)); toast.success("Değerlendirme otomasyonu kaydedildi."); } catch (caught) { toast.error(caught instanceof Error ? caught.message : "Değerlendirme otomasyonu kaydedilemedi."); } finally { setBusy(null); } };
  const runReview = async () => { setBusy("review-run"); try { const result = await adminRequest<{ sent?: number; failed?: number; skipped?: number }>("/api/review-automation/cron", { method: "POST", body: "{}" }); toast.success(`${result.sent || 0} değerlendirme maili gönderildi${result.failed ? `, ${result.failed} hata` : ""}${result.skipped ? ` · ${result.skipped} atlandı` : ""}.`); } catch (caught) { toast.error(caught instanceof Error ? caught.message : "Değerlendirme otomasyonu çalıştırılamadı."); } finally { setBusy(null); } };
  const runAbandoned = async () => { setBusy("abandoned-run"); try { const result = await adminRequest<{ sent?: number; failed?: number }>("/api/email/abandoned-cart/run", { method: "POST", body: "{}" }); toast.success(`${result.sent || 0} terk sepet maili gönderildi${result.failed ? `, ${result.failed} hata` : ""}.`); } catch (caught) { toast.error(caught instanceof Error ? caught.message : "Terk sepet otomasyonu çalıştırılamadı."); } finally { setBusy(null); } };
  const preview = useMemo(() => previewKey === "review_request" ? { subject: review.subject, headline: "Deneyimini paylaş, indirimin hesabına tanımlansın", body: review.template.replace(/\{\{customer_name\}\}/g, "ROSTA Coffee Co. müşterisi").replace(/\{\{review_url\}\}/g, "").replace(/\{\{discount_percent\}\}/g, String(review.discountPercent)), cta: "Değerlendir" } : { subject: previewKey === "abandoned_cart_3" ? "Son hatırlatma: Sepetine dön" : "Sepetindeki parçalar seni bekliyor", headline: previewKey === "abandoned_cart_3" ? "Sepetin için son hatırlatma" : "Sepetin seni bekliyor", body: "Ödemeye kadar geldiğin ROSTA ürünleri hâlâ seni bekliyor. Sana özel fırsatla kaldığın yerden devam edebilirsin.", cta: "Ödemeye Devam Et" }, [previewKey, review]);

  return <div className="space-y-4 animate-fade-in" data-exact-base44-page="automations">
    <ExactPageHeader title="E-posta Otomasyonları" subtitle="Terk sepet ve teslim sonrası değerlendirme akışları" actions={<><Link href="/email"><ExactButton variant="secondary" size="sm"><ArrowLeft className="h-4 w-4" /> E-posta merkezi</ExactButton></Link><ExactIconButton icon={RefreshCw} label="Yenile" variant="secondary" onClick={() => void load()} loading={loading} /></>} />
    <div className="grid grid-cols-2 lg:grid-cols-4 gap-3"><ExactMetricCard label="Terk Sepet" value={abandoned.enabled ? 1 : 0} icon={Sparkles} /><ExactMetricCard label="İlk Gönderim" value={abandoned.firstDelayHours} suffix=" sa" icon={Clock3} /><ExactMetricCard label="Yorum İsteği" value={review.enabled ? 1 : 0} icon={Mail} /><ExactMetricCard label="Yorum Gecikmesi" value={review.delayDaysAfterDelivered} suffix=" gün" icon={Clock3} /></div>
    <div className="grid xl:grid-cols-[1fr_1fr_0.9fr] gap-3 items-start">
      <ExactDataCard title="Terk Sepet Akışı"><Toggle checked={abandoned.enabled} onChange={(enabled) => setAbandoned((current) => ({ ...current, enabled }))} label="Otomasyonu aktif tut" description="Zamanı gelen izinli sepetlere otomatik gönderim yapılır." /><div className="grid grid-cols-3 gap-2 mt-3"><ExactField label="1. mail"><input type="number" min="1" max="72" value={abandoned.firstDelayHours} onChange={(event) => setAbandoned((current) => ({ ...current, firstDelayHours: Number(event.target.value) }))} className={exactFormInputClass} /></ExactField><ExactField label="2. mail"><input type="number" min="1" max="72" value={abandoned.secondDelayHours} onChange={(event) => setAbandoned((current) => ({ ...current, secondDelayHours: Number(event.target.value) }))} className={exactFormInputClass} /></ExactField><ExactField label="3. mail"><input type="number" min="1" max="72" value={abandoned.thirdDelayHours} onChange={(event) => setAbandoned((current) => ({ ...current, thirdDelayHours: Number(event.target.value) }))} className={exactFormInputClass} /></ExactField></div><div className="mt-3 grid grid-cols-3 gap-2">{[abandoned.firstDelayHours, abandoned.secondDelayHours, abandoned.thirdDelayHours].map((hours, index) => <button key={index} type="button" onClick={() => setPreviewKey(`abandoned_cart_${index + 1}` as PreviewKey)} className={`p-3 radius-small text-left border transition-all ${previewKey === `abandoned_cart_${index + 1}` ? "border-accent bg-accent-soft" : "border-border-subtle bg-surface-secondary"}`}><span className="text-[10px] text-subtle">{index + 1}. adım</span><p className="text-sm font-bold text-main">{index === 0 ? hours : `+${hours}`} saat</p></button>)}</div><div className="flex gap-2 mt-4"><ExactButton size="sm" onClick={() => void saveAbandoned()} loading={busy === "abandoned-save"}><Save className="h-4 w-4" /> Kaydet</ExactButton><ExactButton variant="secondary" size="sm" onClick={() => void runAbandoned()} loading={busy === "abandoned-run"}><Send className="h-4 w-4" /> Şimdi çalıştır</ExactButton></div></ExactDataCard>
      <ExactDataCard title="Değerlendirme İsteği"><Toggle checked={review.enabled} onChange={(enabled) => setReview((current) => ({ ...current, enabled }))} label="Değerlendirme otomasyonu" description="Teslim edilen siparişlere 1 gün sonra yorum isteği gönderir." /><div className="grid sm:grid-cols-2 gap-3 mt-3"><ExactField label="Teslimden sonra"><input type="number" min="1" max="14" value={review.delayDaysAfterDelivered} onChange={(event) => setReview((current) => ({ ...current, delayDaysAfterDelivered: Number(event.target.value) }))} className={exactFormInputClass} /></ExactField><ExactField label="Yorum indirimi %"><input type="number" min="0" max="100" value={review.discountPercent} onChange={(event) => setReview((current) => ({ ...current, discountPercent: Number(event.target.value) }))} className={exactFormInputClass} /></ExactField></div><ExactField label="Mail konusu" className="mt-3"><input value={review.subject} onChange={(event) => setReview((current) => ({ ...current, subject: event.target.value }))} className={exactFormInputClass} /></ExactField><ExactField label="Mail metni" className="mt-3"><textarea rows={6} value={review.template} onChange={(event) => setReview((current) => ({ ...current, template: event.target.value }))} className={`${exactFormInputClass} min-h-36`} /></ExactField><div className="flex gap-2 mt-4"><ExactButton size="sm" onClick={() => void saveReview()} loading={busy === "review-save"}><Save className="h-4 w-4" /> Kaydet</ExactButton><ExactButton variant="secondary" size="sm" onClick={() => void runReview()} loading={busy === "review-run"}><Send className="h-4 w-4" /> Şimdi çalıştır</ExactButton></div></ExactDataCard>
      <ExactDataCard title="Canlı E-posta Önizlemesi" action={<ExactButton variant="tertiary" size="sm" onClick={() => setPreviewKey("review_request")}><Eye className="h-3.5 w-3.5" /> Yorum maili</ExactButton>}><div className="radius-card overflow-hidden border border-border-subtle bg-white"><div className="h-20 bg-gradient-to-br from-[hsl(var(--accent))] to-[hsl(var(--accent-hover))] flex items-center justify-center"><span className="text-white font-bold tracking-wide">ROSTA COFFEE CO.</span></div><div className="p-5"><p className="text-[10px] uppercase tracking-wide text-subtle">{preview.subject}</p><h3 className="text-xl font-bold text-main mt-2">{preview.headline}</h3><p className="text-sm text-muted mt-3 leading-relaxed">{preview.body}</p><button type="button" className="mt-5 h-10 px-5 radius-control bg-accent text-white text-sm font-semibold">{preview.cta}</button></div></div></ExactDataCard>
    </div>
  </div>;
}