export const ruthSemanticTokenNames = {
  color: {
    canvas: "--ruth-color-canvas",
    surface: "--ruth-color-surface",
    surfaceMuted: "--ruth-color-surface-muted",
    surfaceElevated: "--ruth-color-surface-elevated",
    surfaceInverse: "--ruth-color-surface-inverse",
    textPrimary: "--ruth-color-text-primary",
    textMuted: "--ruth-color-text-muted",
    textInverse: "--ruth-color-text-inverse",
    textOnLight: "--ruth-color-text-on-light",
    textOnAction: "--ruth-color-text-on-action",
    accent: "--ruth-color-accent",
    accentSoft: "--ruth-color-accent-soft",
    accentStrong: "--ruth-color-accent-strong",
    accentWash: "--ruth-color-accent-wash",
    borderSubtle: "--ruth-color-border-subtle",
    borderStrong: "--ruth-color-border-strong",
    focus: "--ruth-color-focus",
    selected: "--ruth-color-selected",
    overlay: "--ruth-color-overlay",
    success: "--ruth-color-success",
    successSoft: "--ruth-color-success-soft",
    successText: "--ruth-color-success-text",
    warning: "--ruth-color-warning",
    warningSoft: "--ruth-color-warning-soft",
    warningText: "--ruth-color-warning-text",
    danger: "--ruth-color-danger",
    dangerSoft: "--ruth-color-danger-soft",
    dangerText: "--ruth-color-danger-text",
    info: "--ruth-color-info",
    infoSoft: "--ruth-color-info-soft",
    infoText: "--ruth-color-info-text",
    neutral: "--ruth-color-neutral",
    neutralSoft: "--ruth-color-neutral-soft",
    neutralText: "--ruth-color-neutral-text",
    statusAccent: "--ruth-color-status-accent",
    statusAccentSoft: "--ruth-color-status-accent-soft",
    statusAccentText: "--ruth-color-status-accent-text",
  },
  font: {
    display: "--ruth-font-display",
    body: "--ruth-font-body",
  },
} as const;

export const ruthSemanticDefaults = {
  color: {
    canvas: "#111111",
    surface: "#242424",
    surfaceMuted: "#242424",
    surfaceElevated: "#242424",
    surfaceInverse: "#FBF3E6",
    textPrimary: "#FBF3E6",
    textMuted: "color-mix(in srgb, #FBF3E6 72%, transparent)",
    textInverse: "#FBF3E6",
    textOnLight: "#111111",
    textOnAction: "#FFFFFF",
    accent: "#C94A40",
    accentSoft: "color-mix(in srgb, #C94A40 15%, transparent)",
    accentStrong: "#38251C",
    accentWash: "color-mix(in srgb, #C94A40 15%, transparent)",
    borderSubtle: "color-mix(in srgb, #C8A77D 42%, transparent)",
    borderStrong: "#C8A77D",
    focus: "#C94A40",
    selected: "#C94A40",
    overlay: "color-mix(in srgb, #111111 72%, transparent)",
    success: "#1BA786",
    successSoft: "#E3F8ED",
    successText: "#147B63",
    warning: "#D99620",
    warningSoft: "#FFF4D6",
    warningText: "#9B6B17",
    danger: "#E1606B",
    dangerSoft: "#FFE5E8",
    dangerText: "#D62937",
    info: "#4F94E8",
    infoSoft: "#EBF3FF",
    infoText: "#1C71D9",
    neutral: "#858993",
    neutralSoft: "#EBECF0",
    neutralText: "#60636C",
    statusAccent: "#C9A33B",
    statusAccentSoft: "#F6EBC6",
    statusAccentText: "#3B2D0D",
  },
  font: {
    display: '"Cinzel", Georgia, serif',
    body: '"Montserrat", Arial, sans-serif',
  },
} as const;

export type RuthSemanticTokenNames = typeof ruthSemanticTokenNames;
export type RuthSemanticDefaults = typeof ruthSemanticDefaults;
