-- ROSTA panel health/read-model/worker runtime.
-- Service-role only. No Ruth domains, data sources or external project dependencies.

create table if not exists public.panel_read_models (
  key text primary key,
  route_path text not null,
  scope text not null default 'general',
  payload jsonb not null default '{}'::jsonb,
  status text not null default 'healthy' check (status in ('healthy','stale','error')),
  revision bigint not null default 1,
  refreshed_at timestamptz not null default now(),
  expires_at timestamptz,
  duration_ms integer,
  last_error text,
  metadata jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

create unique index if not exists panel_read_models_route_path_idx on public.panel_read_models(route_path);
create index if not exists panel_read_models_scope_idx on public.panel_read_models(scope, refreshed_at desc);
create index if not exists panel_read_models_freshness_idx on public.panel_read_models(status, refreshed_at desc);

create table if not exists public.panel_sync_requests (
  id bigint generated by default as identity primary key,
  scope text not null,
  reason text not null default 'data_changed',
  dedupe_key text not null,
  status text not null default 'pending' check (status in ('pending','running','done','failed')),
  attempts integer not null default 0 check (attempts >= 0),
  requested_at timestamptz not null default now(),
  started_at timestamptz,
  completed_at timestamptz,
  last_error text,
  metadata jsonb not null default '{}'::jsonb
);

create unique index if not exists panel_sync_requests_active_dedupe_idx
  on public.panel_sync_requests(dedupe_key)
  where status in ('pending','running');
create index if not exists panel_sync_requests_pending_idx
  on public.panel_sync_requests(status, requested_at);

create table if not exists public.panel_sync_runs (
  id uuid primary key default gen_random_uuid(),
  worker_id text not null,
  status text not null default 'running' check (status in ('running','healthy','degraded','failed')),
  requested_scopes jsonb not null default '[]'::jsonb,
  refreshed_count integer not null default 0 check (refreshed_count >= 0),
  failed_count integer not null default 0 check (failed_count >= 0),
  details jsonb not null default '{}'::jsonb,
  started_at timestamptz not null default now(),
  completed_at timestamptz
);

create index if not exists panel_sync_runs_started_idx on public.panel_sync_runs(started_at desc);

create table if not exists public.panel_service_health_state (
  service_key text primary key,
  status text not null default 'healthy' check (status in ('healthy','degraded','unhealthy')),
  detail text,
  first_seen_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  last_alerted_at timestamptz,
  recovered_at timestamptz,
  metadata jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

create table if not exists public.commerce_recovery_policies (
  engine_key text primary key,
  enabled boolean not null default true,
  stuck_after_seconds integer not null check (stuck_after_seconds between 15 and 86400),
  base_backoff_seconds integer not null check (base_backoff_seconds between 1 and 3600),
  max_backoff_seconds integer not null check (max_backoff_seconds between 1 and 86400),
  max_auto_retries integer not null check (max_auto_retries between 1 and 100),
  safe_dead_letter_replay boolean not null default false,
  metadata jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

create table if not exists public.commerce_recovery_events (
  id uuid primary key default gen_random_uuid(),
  engine_key text not null,
  action text not null,
  status text not null check (status in ('detected','repairing','recovered','manual_review','failed','noop')),
  item_count integer not null default 0 check (item_count >= 0),
  detail text,
  metadata jsonb not null default '{}'::jsonb,
  occurred_at timestamptz not null default now()
);

create index if not exists commerce_recovery_events_time_idx
  on public.commerce_recovery_events(occurred_at desc);
create index if not exists commerce_recovery_events_engine_time_idx
  on public.commerce_recovery_events(engine_key, occurred_at desc);

create table if not exists public.commerce_worker_config (
  id boolean primary key default true check (id),
  worker_secret text not null default (
    replace(gen_random_uuid()::text,'-','') || replace(gen_random_uuid()::text,'-','')
  ),
  enabled boolean not null default true,
  updated_at timestamptz not null default now()
);

insert into public.commerce_worker_config(id)
values(true)
on conflict(id) do nothing;

insert into public.commerce_recovery_policies(
  engine_key, enabled, stuck_after_seconds, base_backoff_seconds,
  max_backoff_seconds, max_auto_retries, safe_dead_letter_replay, metadata
) values
  ('commerce-queues', true, 120, 15, 1800, 8, false, '{"owner":"rosta-worker","mode":"lease-recovery"}'::jsonb),
  ('panel-sync', true, 120, 10, 300, 8, true, '{"owner":"rosta-panel","mode":"scoped-retry"}'::jsonb),
  ('read-model', true, 30, 10, 300, 8, true, '{"owner":"rosta-panel","mode":"scoped-rebuild"}'::jsonb)
on conflict(engine_key) do update set
  enabled=excluded.enabled,
  stuck_after_seconds=excluded.stuck_after_seconds,
  base_backoff_seconds=excluded.base_backoff_seconds,
  max_backoff_seconds=excluded.max_backoff_seconds,
  max_auto_retries=excluded.max_auto_retries,
  safe_dead_letter_replay=excluded.safe_dead_letter_replay,
  metadata=excluded.metadata,
  updated_at=now();

alter table public.panel_read_models enable row level security;
alter table public.panel_sync_requests enable row level security;
alter table public.panel_sync_runs enable row level security;
alter table public.panel_service_health_state enable row level security;
alter table public.commerce_recovery_policies enable row level security;
alter table public.commerce_recovery_events enable row level security;
alter table public.commerce_worker_config enable row level security;

revoke all privileges on table public.panel_read_models from public,anon,authenticated;
revoke all privileges on table public.panel_sync_requests from public,anon,authenticated;
revoke all privileges on table public.panel_sync_runs from public,anon,authenticated;
revoke all privileges on table public.panel_service_health_state from public,anon,authenticated;
revoke all privileges on table public.commerce_recovery_policies from public,anon,authenticated;
revoke all privileges on table public.commerce_recovery_events from public,anon,authenticated;
revoke all privileges on table public.commerce_worker_config from public,anon,authenticated;

grant select,insert,update,delete on table public.panel_read_models to service_role;
grant select,insert,update,delete on table public.panel_sync_requests to service_role;
grant select,insert,update,delete on table public.panel_sync_runs to service_role;
grant select,insert,update,delete on table public.panel_service_health_state to service_role;
grant select,insert,update,delete on table public.commerce_recovery_policies to service_role;
grant select,insert,update,delete on table public.commerce_recovery_events to service_role;
grant select,insert,update,delete on table public.commerce_worker_config to service_role;
grant usage,select on sequence public.panel_sync_requests_id_seq to service_role;
