import { LegalDocument, LegalList } from "@/components/legal/LegalDocument";
export const metadata={title:"KVKK Aydınlatma Metni",description:"6698 sayılı Kanun kapsamında aydınlatma metni."};
export default function KvkkPage(){return <LegalDocument title="KVKK Aydınlatma Metni" description="Kişisel verilerinizin işlenmesine ilişkin veri sorumlusu aydınlatması." sections={[
 {title:"1. Veri Sorumlusu",content:<p>6698 sayılı Kişisel Verilerin Korunması Kanunu kapsamında veri sorumlusu; <strong>Görkem Çirik (Ruth Istanbul)</strong>, vergi dairesi Bayrampaşa, vergi numarası 2571309841, adres: Vatan Mahallesi, Küçük Sokak No: 2 Daire: 1, Bayrampaşa / İstanbul, e-posta: ruthistanbull@gmail.com’dur.</p>},
 {title:"2. İşlenen Kişisel Veriler",content:<LegalList><li>Kimlik, iletişim, adres ve üyelik bilgileri.</li><li>Doğum tarihi ve sadakat programı hareketleri.</li><li>Sipariş, ödeme, fatura, teslimat, iade/değişim ve destek kayıtları.</li><li>Ticari elektronik ileti tercihleri ve onay kayıtları.</li><li>IP, cihaz, işlem güvenliği, trafik ve çerez kayıtları.</li></LegalList>},
 {title:"3. İşleme Amaçları ve Hukuki Sebepler",content:<><p>Veriler; sözleşmenin kurulması ve ifası, hukuki yükümlülüklerin yerine getirilmesi, bir hakkın tesisi/kullanılması/korunması, veri sorumlusunun meşru menfaati ve gerekli olduğu durumlarda açık rıza veya ticari ileti onayı hukuki sebeplerine dayanarak işlenir.</p><LegalList><li>Üyelik, sipariş, ödeme, kargo, iade, değişim ve destek işlemleri.</li><li>Muhasebe, vergi, tüketici ve elektronik ticaret yükümlülükleri.</li><li>Güvenlik, dolandırıcılık önleme ve denetim.</li><li>Onay verilmişse kampanya ve pazarlama iletişimi.</li></LegalList></>},
 {title:"4. Aktarım",content:<p>Veriler; PayTR, Sürat Kargo, HepsiJet, barındırma/veritabanı, e-posta, bilişim, mali müşavirlik ve yetkili kamu kurumlarıyla amaçla sınırlı olarak paylaşılabilir. Yurt dışına aktarım söz konusu olduğunda KVKK’nın 9. maddesindeki şartlar ve uygun güvenceler uygulanır.</p>},
 {title:"5. Toplama Yöntemi",content:<p>Veriler; web sitesi formları, üyelik ve sipariş işlemleri, çerezler, e-posta, telefon, WhatsApp, kargo ve ödeme hizmetlerinden elektronik veya fiziki yollarla toplanır.</p>},
 {title:"6. Haklarınız",content:<><p>KVKK’nın 11. maddesi kapsamındaki haklarınız için kimliğinizi doğrulayan bilgiler ve talebinizle birlikte ruthistanbull@gmail.com adresine veya işletme adresine başvurabilirsiniz.</p><LegalList><li>Verilerinizin işlenip işlenmediğini öğrenme ve bilgi talep etme.</li><li>İşleme amacını ve amaca uygun kullanılıp kullanılmadığını öğrenme.</li><li>Aktarılan üçüncü kişileri bilme.</li><li>Eksik/yanlış verilerin düzeltilmesini, şartları varsa silinmesini veya yok edilmesini isteme.</li><li>Otomatik sistem sonucuna itiraz etme ve zararın giderilmesini talep etme.</li></LegalList></>},
 {title:"7. Başvuru",content:<p>Başvurular, talebin niteliğine göre en kısa sürede ve en geç mevzuatta öngörülen süre içinde sonuçlandırılır. İletişim: ruthistanbull@gmail.com.</p>}
 ]}/>}
