import { LegalDocument, LegalList } from "@/components/legal/LegalDocument";
export const metadata = { title: "Gizlilik Politikası", description: "Ruth Istanbul gizlilik ve veri güvenliği politikası." };
export default function PrivacyPage(){ return <LegalDocument title="Gizlilik Politikası" description="Web sitesi, üyelik, sipariş ve destek süreçlerinde gizliliğin nasıl korunduğunu açıklar." sections={[
 {title:"Toplanan Bilgiler",content:<LegalList><li>Kimlik ve iletişim bilgileri: ad soyad, e-posta, telefon, adres.</li><li>Üyelik ve tercih bilgileri: doğum tarihi, ticari ileti tercihleri, hesap hareketleri.</li><li>Sipariş ve işlem bilgileri: ürünler, tutarlar, kargo, iade/değişim ve müşteri notları.</li><li>Teknik bilgiler: IP, cihaz, tarayıcı, çerezler, trafik ve güvenlik kayıtları.</li></LegalList>},
 {title:"Kullanım Amaçları",content:<LegalList><li>Üyelik, sipariş, ödeme, teslimat, iade/değişim ve destek süreçlerini yürütmek.</li><li>Dolandırıcılığı önlemek, sistem ve hesap güvenliğini sağlamak.</li><li>Kanuni yükümlülükleri yerine getirmek ve uyuşmazlıkları yönetmek.</li><li>Açık tercih verilmişse kampanya ve indirim iletişimi yapmak.</li><li>Çerez tercihlerine göre performans, ölçüm ve reklam çalışmalarını yürütmek.</li></LegalList>},
 {title:"Hizmet Sağlayıcılar",content:<p>Veriler; ödeme için PayTR’ye, teslimat için Sürat Kargo veya HepsiJet’e, barındırma/veritabanı hizmetlerine, e-posta hizmetlerine ve izin verilen ölçüm araçlarına yalnızca gerekli kapsamda aktarılabilir. Hizmet sağlayıcıların yurt dışı altyapısı bulunması halinde aktarım, KVKK’nın yurt dışına aktarım hükümlerine uygun hukuki mekanizmalar çerçevesinde gerçekleştirilir.</p>},
 {title:"Çerezler ve Ölçüm",content:<p>Site; zorunlu oturum ve sepet çerezleri ile tercih verilmesi halinde Google Analytics 4, Meta ve Microsoft Clarity benzeri ölçüm araçlarını kullanabilir. Zorunlu olmayan çerezler için kullanıcı tercihi esas alınır.</p>},
 {title:"Güvenlik ve Saklama",content:<p>Veriler yetkisiz erişime karşı teknik ve idari tedbirlerle korunur; yalnızca işleme amacı ve ilgili mevzuat için gerekli süre boyunca saklanır, süresi dolduğunda silinir, yok edilir veya anonimleştirilir.</p>},
 {title:"İletişim",content:<p>Gizlilik talepleri için <a className="underline" href="mailto:ruthistanbull@gmail.com">ruthistanbull@gmail.com</a> adresine başvurabilirsiniz.</p>}
 ]}/> }
